# -*- coding: utf-8 -*-
"""Web Scarping Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbSH9yuBxzXHar8kOILfjTlceH1OhHSb
"""

import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import re

url="https://www.flipkart.com/search?q=samsung+mobile+phone"
data = requests.get(url)
soup = BeautifulSoup(data.text,'html.parser')
ls = soup.find_all('span',{'class':"_2yAnYN"})
ls=ls[0].get_text()
text=ls.split(' ')
endnumber=text[5]
endnumber=int(endnumber)
endnumber

prod_des = []
sales_price = []
pages_remainder=endnumber%24
if pages_remainder==0:
  pages=endumber/24
else:
  pages=(endnumber/24)+1
for i in range(int(pages)):
  url = 'https://www.flipkart.com/search?q=samsung+mobile+phone&as=on&as-show=on&otracker=AS_Query_HistoryAutoSuggest_1_3_na_na_na&otracker1=AS_Query_HistoryAutoSuggest_1_3_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=samsung+mobile+phone&requestId=5e0b5aa6-b4be-49ac-ad68-060696ff58c8&as-backfill=on&page='+str(i)
  #print(url)
  data = requests.get(url)
  soup = BeautifulSoup(data.text,'html.parser')
  ls = soup.find_all('div',{'class':"_3wU53n"})
  
  for a in ls:
    prod_des.append(a.get_text())
  df = pd.DataFrame({'Product_Description':prod_des})
  
  ls_1 = soup.find_all('div',{'class':"_1vC4OE"})
  #sales_price = []
  for i in range(24):
    #print(ls[i].get_text())
    sales_price.append(ls_1[i].get_text())
  df['Sales_Price'] = sales_price

df

df.to_csv("mobile.csv")